import { CHAT_THEME } from "../constants/theme";

export const PROSE_SX = {
  maxWidth: "100%",
  overflowWrap: "anywhere",
  wordBreak: "break-word",
  "& > *": { background: "transparent", maxWidth: "100%" },
  "& p, & li, & span, & strong, & em, & del, & h1, & h2, & h3, & h4, & h5, & h6": {
    background: "transparent",
    backgroundColor: "transparent",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  "& p": { margin: "0 0 0.8em 0", background: "transparent", overflowWrap: "anywhere" },
  "& p:last-child": { marginBottom: 0 },
  "& h1, & h2, & h3, & h4": {
    fontWeight: 700,
    letterSpacing: "-0.015em",
    lineHeight: 1.3,
    margin: "1.2em 0 0.5em",
    color: CHAT_THEME.textPrimary,
  },
  "& h1:first-child, & h2:first-child, & h3:first-child": { marginTop: 0 },
  "& h1": { fontSize: "1.45em" },
  "& h2": { fontSize: "1.25em" },
  "& h3": { fontSize: "1.1em" },
  "& ul, & ol": { paddingLeft: "1.4em", margin: "0.4em 0 0.8em" },
  "& li": { marginBottom: "0.3em", lineHeight: 1.65 },
  "& li > p": { margin: "0.2em 0" },
  "& strong": { fontWeight: 700, color: CHAT_THEME.textPrimary },
  "& em": { color: "rgba(255,255,255,0.75)", fontStyle: "italic" },
  "& code": {
    fontFamily: "'JetBrains Mono', 'SF Mono', Menlo, monospace",
    fontSize: "0.86em",
    background: "rgba(239,68,68,0.08)",
    border: "1px solid rgba(239,68,68,0.18)",
    borderRadius: "6px",
    padding: "0.1em 0.42em",
    color: "rgba(252,165,165,0.95)",
    fontWeight: 500,
  },
  "& pre code": {
    background: "transparent",
    border: "none",
    padding: 0,
    color: "inherit",
    fontSize: "inherit",
  },
  "& a": { color: "#f87171", textDecoration: "underline", textUnderlineOffset: "3px", transition: "opacity 0.15s" },
  "& a:hover": { opacity: 0.8 },
  "& blockquote": {
    borderLeft: "3px solid rgba(239,68,68,0.5)",
    paddingLeft: "1em",
    color: "rgba(255,255,255,0.65)",
    margin: "0.6em 0",
    fontStyle: "italic",
  },
  "& hr": { border: "none", borderTop: "1px solid rgba(255,255,255,0.1)", margin: "1em 0" },
  "& table": { width: "100%", borderCollapse: "collapse", margin: "0.8em 0" },
  "& th, & td": {
    padding: "0.5em 0.75em",
    border: "1px solid rgba(255,255,255,0.12)",
    textAlign: "left",
  },
  "& th": { background: "rgba(255,255,255,0.06)", fontWeight: 600 },
};
