[tool.poetry]
name = "nvidia_isaac_simulation"
version = "v0.0.0"
description = ""
authors = ["Volkhin Danil <deneal123@mail.ru>"]
readme = "README.md"
homepage = "https://github.com/deneal123/AgentsSwarm/tree/dev"
repository = "https://github.com/deneal123/AgentsSwarm/tree/nvidia_isaac_simulation"
packages = [
  { include = "nvidia_isaac_simulation", from = "src" },
]
exclude = [
    "tests",
    "docs",
    "**/__pycache__",
    "**/*.pyc",
    "**/.ipynb_checkpoints",
]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
dynaconf = "^3.2.13"

[tool.poetry.group.dev.dependencies]
black = "25.1.0"
isort = "6.0.1"
pre-commit = "4.3.0"
pytest = "8.3.3"
pytest-asyncio = "1.2.0"
build = ">=1.4.0,<2.0.0"
twine = ">=6.2.0,<7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
filterwarnings = [
  "ignore::DeprecationWarning:fastapi.openapi.models",
  "ignore::DeprecationWarning:pydantic_core.core_schema",
]
