from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class ProfileRepositoryPort(Protocol):
    async def fetch_user_profile(self, user_id: str) -> Any | None: ...
    async def fetch_user_by_email(self, email: str) -> Any | None: ...
    async def create_user(self, *, email: str, password_hash: str) -> Any: ...
    async def update_user_profile(self, profile: Any) -> Any: ...
    async def delete_user_chat_history(self, user_id: str) -> None: ...


@runtime_checkable
class ProfileCachePort(Protocol):
    async def set_json(self, namespace: str, key: str, value: dict, ttl_seconds: int | None = None) -> None: ...
    async def get_json(self, namespace: str, key: str) -> dict | None: ...
    async def invalidate(self, namespace: str, key: str) -> None: ...
