[pytest]
addopts =
    --cov=service
    --cov=service/agents
    --cov-report=term-missing
    --cov-fail-under=85
filterwarnings =
	ignore:Using extra keyword arguments on `Field` is deprecated.*
	ignore:pkg_resources is deprecated as an API.*
	ignore:.*HTTP_422_UNPROCESSABLE_ENTITY.*
markers =
	integration: mark test as integration (slow, requires external services)
