services:
  vda5050-client:
    image: isaac_sim_ros:ubuntu_24_jazzy
    container_name: vda5050_client
    network_mode: "host"
    ipc: host
    environment:
      - ROS_DISTRO=jazzy
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/jazzy_ws/fastdds.xml
      - ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
    volumes:
      - ${PATH_TO_ISAAC_ROS_WORKSPACES}/build_ws/jazzy/isaac_sim_ros_ws:/jazzy_ws:ro
      - ${PATH_TO_ISAAC_MISSION_CONTROL_CONFIG}/uploaded_maps:/workspace/maps:ro
      - ${PATH_TO_ISAAC_MISSION_CONTROL_CONFIG}/nav2_params:/workspace/nav2_params:ro
      - ./scripts/entrypoint.sh:/entrypoint.sh:ro
    stdin_open: true
    tty: true
    entrypoint: /entrypoint.sh
    restart: unless-stopped
