
version: "3.3"
services:

  wpg:
    image: ${WPG_IMAGE}
    network_mode: "host"
    command: ["python", "scripts/rest_api.py"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  cuopt:
    image: ${CUOPT_IMAGE}
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - CUOPT_SERVER_PORT=${CUOPT_PORT}

  mission-control:
    image: ${MISSION_CONTROL_IMAGE}
    network_mode: "host"
    depends_on:
      - wpg
      - cuopt
    command: ["--config", "/tmp/config/multiple_robot_carter_office_navigation.yaml", "--verbose", "INFO"]
    volumes:
      - type: bind
        source: ${CONFIG_DIR}
        target: /tmp/config/

  # Optional UI for waypoint selection, which can be used to test the mission control service. It is not required for the mission control to function.
  waypoint_ui:
    build:
      context: ../MissionControl
      dockerfile: waypoint_selection_ui/Dockerfile
    network_mode: "host"
    ports:
      - "${WAYPOINT_PORT}:${WAYPOINT_PORT}"
    volumes:
      - ../MissionControl/waypoint_selection_ui/uploads/maps:/app/uploads/maps
      - ../MissionControl/waypoint_selection_ui/uploads/configs:/app/uploads/configs
    environment:
      - PYTHONUNBUFFERED=1
      - WAYPOINT_HOST=${WAYPOINT_HOST}
      - WAYPOINT_PORT=${WAYPOINT_PORT}
      - MISSION_CONTROL_API_URL=http://${MISSION_CONTROL_HOST}:${MC_PORT}/api/v1
