services:
  vda5050-client:
    image: osrf/ros:jazzy-desktop
    container_name: vda5050_client
    network_mode: "host"
    ipc: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISTRO=jazzy
      - TERM=xterm-256color
    volumes:
      - /root/projects/workspace_isaac_simulation/IsaacSim-ros_workspaces/build_ws/jazzy/isaac_sim_ros_ws:/jazzy_ws:ro
      - /root/projects:/workspace/projects:ro
      - ./scripts/entrypoint.sh:/entrypoint.sh:ro
    stdin_open: true
    tty: true
    entrypoint: /entrypoint.sh
    restart: unless-stopped
