FROM python:3.13-slim

ARG NEXUS_PYPI_INDEX_URL

ENV HOME="/dude"
ENV PYTHONPATH=$HOME

RUN groupadd -g 999 dudes && \
    useradd -u 999 -m -g dudes -s /bin/bash dude && \
    mkdir -p ${HOME} && chown dude:dudes $HOME

RUN mkdir -p /var/lib/app/storage && chown -R dude:dudes /var/lib/app

WORKDIR ${HOME}

RUN apt-get update && apt-get install -y curl build-essential netcat-openbsd \
    gcc \
    libpq-dev \
    postgresql-client \
    cargo \
    rustc \
    gosu \
    && rm -rf /var/lib/apt/lists/*

RUN python -m pip install -i "${NEXUS_PYPI_INDEX_URL:-https://pypi.org/simple}" --disable-pip-version-check --no-cache-dir uv

COPY --chown=dude:dudes ./pyproject.toml ./uv.lock ${HOME}/

RUN uv sync --frozen

# Install psycopg2-binary for alembic migrations
RUN uv add psycopg2-binary

ENV PATH="${HOME}/.venv/bin:$PATH"

# For dev environment, we don't copy source code - it will be mounted as volume
COPY --chown=dude:dudes ./alembic ${HOME}/alembic
COPY --chown=dude:dudes ./docker/entrypoints.sh ${HOME}
COPY --chown=dude:dudes ./docker/docker-entrypoint.sh ${HOME}

RUN chmod +x ${HOME}/entrypoints.sh ${HOME}/docker-entrypoint.sh

ENTRYPOINT ["/dude/docker-entrypoint.sh"]

CMD ["server"]
